spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    cache: false
  sql:
    init:
      mode: always
  application:
    name: mykkumi-server
  config:
    import:
      - 'aws-secretsmanager:dev/mykkumi/mysql'
      - 'aws-secretsmanager:dev/mykkumi/s3'
      - 'aws-secretsmanager:dev/mykkumi/jwt'
      - 'aws-secretsmanager:dev/mykkumi/oauth'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_host}:${db_port}/dbMykkumiDev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${kakao_client_id}
            client-secret: ${kakao_client_secret}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: ${s3_bucket_name}
    credentials:
      access-key: ${s3_access_key}
      secret-key: ${s3_secret_key}
    region:
      auto: false
      static: ${region}
      use-default-aws-region-chain: true
    stack:
      auto: false

springdoc:
  packages-to-scan: com.swmarastro.mykkumiserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

jwt:
  issuer: ${jwt_issuer}
  secret_key: ${jwt_secret_key}
  access-token-expired-time: 3600000
